# Generated by Django 5.2.3 on 2025-06-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha del lunes que inicia la semana', unique=True)),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada')], default='draft', help_text='Estado de la semana', max_length=10)),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'Semanas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('estimated_pizzas', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='weeks.week')),
            ],
            options={
                'verbose_name': 'Registro diario',
                'verbose_name_plural': 'Registros diarios',
                'ordering': ['weekday'],
                'unique_together': {('week', 'weekday')},
            },
        ),
    ]
